version: "3"
services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
  express:
    build: ./backend
    ports:
      - "4000:4000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "8889:8889"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
